### ISSUE TITLE
Not working in 2.1

### ISSUE THREAD

**Issue by Spacebarlife** [hssm/anki-addons#24]
Error 
An error occurred. 

Debug info:
Anki 2.1.13 (3ba55990) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.12.6
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Multi-column note editor

Caught exception:
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 87, in _onCmd
  File "aqt/webview.py", line 368, in _onBridgeCmd
  File "<decorator-gen-70>", line 2, in onBridgeCmd
  File "anki/hooks.py", line 74, in decorator_wrapper
  File "anki/hooks.py", line 68, in repl
  File "/Users/ss/Library/Application Support/Anki2/addons21/3491767031/__init__.py", line 220, in myOnBridgeCmd
    self.ccSpin.blockSignals(True)
<class 'AttributeError'>: 'Editor' object has no attribute 'ccSpin'

**Comment by hssm** [comment]
I'm pretty sure this is caused by the Night Mode add-on. If I recall, it's replacing a component that this add-on hooks into, eliminating the effects of the hook.

I won't commit any time to resolving this issue since the add-on itself is working correctly and is using hooks in a standard way. The problem is either a limitation in Anki's add-on system or a greedy approach in the Night Mode (or maybe a different) add-on and it needs to play nicer.

**Comment by Spacebarlife** [comment]
thank you for the prompt follow up! Much appreciated
